### ISSUE TITLE
web app not displaying mapped reads for some genomes - usually when the read count is high

### ISSUE THREAD

**Issue by morungos** [capsid/capsid-webapp#20]
web app is not displaying mapped reads for some genomes (usually when the read count is high). for example see:

http://vr-www.oicr.on.ca:8080/capsid/jbrowse/show/NC_012759?track=0091f01b-7546-4c53-8825-66ea03a1418d

Originally FERV-169

**Comment by iborozan** [comment]
When zooming in the histograms and reads are displayed.

**Comment by morungos** [comment]
Having moved to genome maps, this appears to be resolved. We're using histograms directly, and it's worked fairly well so for with large scale data. If it breaks, open a new ticket.
