### ISSUE TITLE
reads not properly displayed by the browser 

### ISSUE THREAD

**Issue by iborozan** [capsid/capsid-webapp#33]
For example in the case of the Enterobacteria phage phiX174 we should see a high coverage across the whole of the genome but only few reads appear in the browser (please see below)

https://vr-www1.oicr.on.ca/browse/show/NC_001422/ova_oicr/OVCA_0017

**Comment by morungos** [comment]
All tests OK. Seems likely to be an old cached JS file. Make sure to refresh the page and update the JS scripts.
