### ISSUE TITLE
background filter seems to be missing

### ISSUE THREAD

**Issue by iborozan** [capsid/capsid-webapp#38]

**Comment by morungos** [comment]
I'm not entirely sure what this means. Both are there. That's what "Low max gene coverage" and "Low genome coverage" actually do, i.e., in both cases "low" means, "lower than the background". Is there some other filter that we need to implement? If so, that's primarily a pipeline task.

**Comment by iborozan** [comment]
Low max gene coverage should filter out genomes that have "max gene coverage" < 0.5. 
Gene coverage lower than in the background model should filter genomes that have "average genome coverage" <= "average genome coverage" in the background model (done by the pipeline) 
Genome coverage lower than in the background model should filter genomes that have "genome coverage" <= "genome coverage" in the background model (done by the pipeline)

**Comment by morungos** [comment]
Yes, that's how it's written to work -- unless you think they are actually working in a different way, I think it's the labelling that is misleading. "Low genome coverage" is with respect to the background model. So is "Below average genome coverage". Problem is, the labels are now getting very complicated to understand. Correct ones would be "Below background average gene coverage" and "Below background genome coverage" -- I was just running out of room, and the actual labels used internally omit all this extra explanation.

**Comment by iborozan** [comment]
OK. I'll leave "Low max gene coverage". I guess we will need to label the other two in such a way that will make it  more obvious that they are compared to the bg model and without running out of room.
