### ISSUE TITLE
reads that align to both human and a pathogen should be labeled with a different color (red)

### ISSUE THREAD

**Issue by iborozan** [capsid/capsid-webapp#72]
If the read maps to both human and pathogen it is flagged with 'isRef': 1. (see the code below in the pipeline script). 
...
def update_isref(readId):
    ''' '''

```
db.mapped.update({'readId': readId, 'alignmentId':meta.alignment['_id']},
                 {'$set': {'isRef': 1}}, False, False, False, True)
```

**Comment by morungos** [comment]
See commit: 70e8c5b90007fe684195d240cccb9a76291da167
