### ISSUE TITLE
Grails 2.4 now breaks passwords with bcrypt

### ISSUE THREAD

**Issue by morungos** [capsid/capsid-webapp#80]
The default Grails behavour now breaks password validation. The workaround is to use the following in your `~/.grails/capsid-config.groovy`:

```
environments {
  development {
    grails.plugin.springsecurity.ldap.active = false
    grails.plugin.springsecurity.password.algorithm = 'SHA-256'
    grails.plugin.springsecurity.password.hash.iterations = 1
  }
}
```

**Comment by morungos** [comment]
Well, the workaround doesn't always work.

**Comment by morungos** [comment]
So the recommended solution is now committed in 856de19. Delete the old entries above from `~/.grails/capsid-config.groovy`, and then update from `develop`. Also remove the old admin user, and its associated role, from the database. So after cleaning the file, something like this should work.

``` shell
$ cd capsid-webapp-app
$ mongo capsid
> var userId = db.user.findOne({username: 'admin'})['_id']
> db.user.remove({_id: userId})
> db.userRole.remove({user: userId})
> quit()
$ git checkout develop
$ git pull
$ mvn grails:run-app
```

This should allow logins. Newly created users do also work, although the email might not send on OSX unless configured right. You might find a pending message in `/var/spool/postfix/active/`

**Comment by davidcoffey** [comment]
This corrected my problem!  I am now able to login for the first time using the username: admin and password: admin.
